CREATE TABLE FTP_USER (      
   LOGIN_ID VARCHAR(64) NOT NULL PRIMARY KEY,       
   PASSWORD VARCHAR(64),      
   HOME_DIR VARCHAR(128) NOT NULL,             
   ENABLED VARCHAR(8) NOT NULL,    
   WRITE_PERM VARCHAR(8) NOT NULL,       
   IDLE_TIME INT NOT NULL,             
   UPLOAD_RATE INT NOT NULL,             
   DOWNLOAD_RATE INT NOT NULL
)
